import { CardHeader,Card, Container,FormControl,Form,Row,Col, ButtonGroup,Button,Nav } from "react-bootstrap"
import { Link } from "react-router-dom"
function NameComponent(){
    return(<div  >
          <div className="l1">
     <h3>Questions</h3>
     <p>A questions is a keyword or label that categorizes your question with other, similar questions. Using <br>
     </br>the right question makes it easier for others to find and answer your question.</p>
     <p style={{color:'blue'}}>Show all tag synonyms</p>
    
     <Row>
          <Col sm={3}>
            <Form.Group>
              <Form.Control type="text" placeholder="filter by question name" />
            </Form.Group>
          </Col>
         < Col sm={2}>
          <ButtonGroup>
          <Button variant="outline-dark"> <Nav.Link  href="/popular"> popular</Nav.Link></Button>
    
       
          <Button variant="outline-dark">  <Nav.Link  href="/name"> Name</Nav.Link></Button>
        
          <Button variant="outline-dark"><Nav.Link  href="/asknew"> New</Nav.Link></Button>
           
          </ButtonGroup>
          </Col>
          
          </Row><br></br>


          <Link to="/article"   style={{ textDecoration: 'none' }}>
        <div className="grid-container">
      <div className="grid-item"><Button variant="secondary" size="sm">.a</Button>
      <p style={{fontSize:"13px"}}>A static library of object code in UNIX/Linux that can be used by the link editor to create an executable program.</p>
      <p  style={{fontSize:"13px"}}>  147 question 5 asked this year</p>

      </div>
      <div className="grid-item">


      <Button variant="secondary" size="sm">.ajax</Button>
     <p    style={{fontSize:"13px"}}></p>
     <p  style={{fontSize:"13px"}}>0 questions</p>
      
      </div>
      <div className="grid-item">
      <Button variant="secondary" size="sm">.app</Button>
      <p    style={{fontSize:"13px"}}> .app is an extension given to application bundles on Mac OS X.</p>
      <p    style={{fontSize:"13px"}}>163 questions
9 asked this year</p>
      </div>
   
    </div><br></br>
    </Link>


    <Link to="/article"   style={{ textDecoration: 'none' }}>
    <div className="grid-container">
      <div className="grid-item">
      <Button variant="secondary" size="sm">.aspxauth</Button>
      <p    style={{fontSize:"13px"}}>Cookie generated by remote server that identifies the user and allows authentication to the server. The contents of the cookie is signed and encrypted. </p>
      <p    style={{fontSize:"13px"}}> 64 questions
4 asked this year</p>
      </div>
      <div className="grid-item">

      <Button variant="secondary" size="sm">.avi</Button>
      <p    style={{fontSize:"13px"}}>     </p>
      <p    style={{fontSize:"13px"}}>0 questions</p>
      </div>
      <div className="grid-item">
        
      <Button variant="secondary" size="sm">.bash-profile</Button>
      <p    style={{fontSize:"13px"}}>     </p>
      <p    style={{fontSize:"13px"}}>0 questions</p>

      </div>
   </div><br></br>
   </Link>

   <Link to="/article"   style={{ textDecoration: 'none' }}>
      
   <div className="grid-container">
      <div className="grid-item"><Button variant="secondary" size="sm">.bashrc</Button>
      <p style={{fontSize:"13px"}}> </p>
      <p  style={{fontSize:"13px"}}> 0 questions</p>
      </div>
      <div className="grid-item">  


      <Button variant="secondary" size="sm">.bat</Button>
     <p    style={{fontSize:"13px"}}></p>
     <p  style={{fontSize:"13px"}}>0 question</p>
      
      </div>
      <div className="grid-item">
      <Button variant="secondary" size="sm">.class-file</Button>
      <p    style={{fontSize:"13px"}}> Class files are the format used by the Java Virtual Machine.</p>
      <p    style={{fontSize:"13px"}}>283 questions
4 asked this year</p>
      </div>
   </div>
   </Link>
    </div>
    </div>)
}
export default NameComponent